### ISSUE TITLE
Undefined method `encode` for URI:Module

### ISSUE THREAD

**Issue by Andriamanitra** [yast/yast-docker#31] opened 2022-01-13 04:15 UTC
Trying to run a docker container using YaST caused the following error to pop up:

```
Internal error. Please report a bug report with logs.
Run save_y2logs to get complete logs.

Caller: /usr/lib64/ruby/gems/3.0.0/gems/docker-api-1.13.2/lib/docker/image.rb:108:in `get'

Details: undefined method `encode' for URI:Module
```

URI.encode method has been deprecated and is not present in new versions of Ruby. This issue has already been fixed in the latest docker-api gem versions (I think since 2.1.0, could be wrong though).

**Comment by teclator** [comment] 2022-01-13 09:52
I just verified that the issue is fixed with docker-api v2.2.0 gem, unfortunately the gem package that we currently have is [rubygem-docker-api-1.13.2](https://build.opensuse.org/package/show/YaST:Head/rubygem-docker-api)

**Comment by teclator** [comment] 2022-01-13 10:09
Ah, we have that version in https://download.opensuse.org/repositories/devel:/languages:/ruby:/extensions/openSUSE_Tumbleweed/

**Comment by dgdavid** [comment] 2022-01-13 11:43
Thank you @Andriamanitra.

Already tracked at https://bugzilla.suse.com/show_bug.cgi?id=1194630 (thanks @teclator!)

**Comment by mvidner** [comment] 2024-03-18 14:15
As noted in the above Bugzilla ticket, we have upgraded to docker-api-2.2.0 around October 2022 and the problem is gone.

Thanks everyone!

**Closed by mvidner** 2024-03-18 14:15 UTC
Labels: tracked
